version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: pridecontrol/node-test:v2
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - run:
          name: "Install Node Package"
          command: npm install
      - run:
          name: "Install K6 and Create Report Folder"
          command: |
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
            echo "deb https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list
            apt-get update
            apt-get -y install k6
            mkdir client/reports
      - run: 
          name: "Install Docker"
          command: |
            apt-get -y install ca-certificates curl gnupg lsb-release apt-utils
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            apt-get update
            apt-get -y install docker.io
            systemctl start docker
            docker run -p 50051:50051 -d pridecontrol/node-test:v2
      # - run:
      #     name: "Launch Server"
      #     command: npm run server &
      #     background: true
      - run:
          name: "Storing Local IP Address"
          command: |
            IPaddress=`node -p "require('ip').address()"`
            echo "$IPaddress"
      - run:
          name: "Run Test"
          command: |
            IPaddress=`node -p "require('ip').address()"`
            echo "IP Address: $IPaddress"
            k6 run -e IPaddress=$IPaddress client/tests/run_test.js --summary-export client/reports/result.json
      - store_artifacts:
          path: client/reports/

workflows:
  Loadtest-Workflow:
    jobs:
      - Build-and-Test
