version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: pridecontrol/node-test
    steps:
      - checkout
      - run: 
          name: "Preparing Test"
          command: |
            npm install
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
            echo "deb https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list
            apt-get update
            apt-get install k6
            mkdir client/reports
      - run:
          name: "Launch Server"
          command: npm run server &
          background: true
      - run:
          name: "Storing Local IP Address"
          command: |
            IPaddress=`node -p "require('ip').address()"`
            echo "$IPaddress"
      - run:
          name: "Run Test"
          command: |
            IPaddress=`node -p "require('ip').address()"`
            echo "IP Address: $IPaddress"
            k6 run -e IPaddress=$IPaddress client/tests/run_test.js --summary-export client/reports/result.json
      - store_artifacts:
          path: reports/

workflows:
  Loadtest-Workflow:
    jobs:
      - Build-and-Test
