version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: node
    steps:
      - checkout
      - run: 
          name: "Preparing Test"
          command: |
            npm install
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
            echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
            sudo apt-get update
            sudo apt-get install k6
            mkdir client/reports
      - run:
          name: "Launch Server"
          command: npm run server
      - run:
          name: "Run Test"
          command: npm run test
      - store_artifacts:
          path: reports/

workflows:
  Loadtest-Workflow:
    jobs:
      - Build-and-Test
