version: 2.1
jobs:
  Build-Server:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build and start Server"
          command: |
            docker build -t image:test .
            docker run --name "grpc-node-server" -p 50051:50051 -d image:test
      - run:
          name: "Storing Local IP Address"
          command: |
            node -p "require('ip').address()" > ip.txt
            cat ip.txt
  Build-Test:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: "Install Node Package"
          command: |
            # apt-get update
            # apt-get install node
            npm install
      - run:
          name: "Install K6 and Create Report Folder"
          command: |
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
            echo "deb https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list
            apt-get update
            apt-get -y install k6
            mkdir client/reports
      - run:
          name: "Run Test"
          command: |
            IPaddress=`cat ip.txt`
            echo "$IPaddress"
            k6 run -e IPaddress=$IPaddress client/tests/run_test.js --summary-export client/reports/result.json
      - store_artifacts:
          path: client/reports/

workflows:
  Loadtest-Workflow:
    jobs:
      - Build-Server
      - Build-Test:
          requires:
            - Build-Server
